---
- hosts: all
  vars_files:
    - vars/main.yml

  tasks:
  
    - name: Modificando contraseña
      copy:
        src: /root/ansible/tomcat-centos/resources/tomcat-users.xml
        dest: "{{directorio_inst}}/conf"
        owner: "{{usuario_servicio}}"
        group: "{{grupo_servicio}}"

    - name: Validando
      systemd:
        name: tomcat.service
        state: stopped
    
    - name: Iniciando
      systemd:
        name: tomcat.service
        state: started
